### ISSUE TITLE
No factory has been set

### ISSUE THREAD

**Issue by pragneshmpatel** [callumbwhyte/sidecar#2]
Hi Callum,
Thanks for sharing your great work.
I am trying to run the umbraco 8 console but I am coming up with error No factory has been set.

Do I miss anything to set?
![image](https://user-images.githubusercontent.com/1867062/81288708-119bc180-905d-11ea-936e-69e2dce9eb7e.png)

**Comment by callumbwhyte** [comment]
Hey @pragneshmpatel!

Thanks for giving the preview of Sidecar a try!

There could be a number of reasons why you are getting this error, and this rather unhelpful error message is coming straight from Umbraco rather than Sidecar. I am working to add something that makes errors a little more user friendly...

Some things to check / try in your config:

- Is your connection string valid? Can you connect to the server and the database with the necessary permissions?

- Do you have the `Umbraco.Core.ConfigurationStatus` app setting and is it set to a valid version number, e.g. `8.6.1`? This version needs to be the same version as your database has been upgraded to.

- Do you have the `Umbraco.Core.Path` app setting and is it set to `~/umbraco`?

Finally, Sidecar currently needs to have the same version of Umbraco installed as you are running elsewhere. By default Sidecar ships with Umbraco 8.1.0, you might need to upgrade this dependency to match the version you are using elsewhere.

Hope this helps, let me know how you get on!

Callum

**Comment by gregorypilar** [comment]
Hello!

I have the same error using 8.6.1

**Comment by gregorypilar** [comment]
Looks like all the files on config folder should be set to Copy Always

**Comment by pragneshmpatel** [comment]
> Looks like all the files on config folder should be set to Copy Always

Thanks @gregorypilar  that worked.
